### ISSUE TITLE
[UI/UX] As a developer, I want understand, what is the impact of committed code on blockchain performance

### ISSUE THREAD

**Issue by cyrcle0** [openmina/mina-frontend#47]
Checklist

- [x] Kickoff with Alex and Zura
- [x] Initial wireframes & UI/UX
---
**Week 8** 
- [x] UI/UX Designs with sidebar interactions
---
**Week 9** 
- [x] Hello World Tutorial to understand dev perspective https://docs.minaprotocol.com/zkapps/tutorials/hello-world
- [x] Reviewed designs
- [x] Scoped down, refocused UI/UX on blocks
---
**Week 10** 
- [x] Reviewed designs
- [x] Added Filters, Layout focused on histograms, Statuses
---
**Week 11** 
- [x] Reviewed designs
- [x] Support FE to develop iteration 0, to get feedback on a live app
---
**Week 12** 
- [x] Reviewed designs
- [x] Feedback addressed: Trends, Compare
---

**TODO**
- [ ] Compare is focused only on CI runs, we need tracing te get merged in develop to compare against develop

**Current Design - iteration 4 WIP -**

![Image](https://user-images.githubusercontent.com/1679939/227921172-4a5b1860-c7c4-4b21-8cbf-3b8765f70d20.png)

![Image](https://user-images.githubusercontent.com/1679939/227921208-6ab3c59d-bf57-4f10-b522-70cfd9147a0e.png)

![Image](https://user-images.githubusercontent.com/1679939/227921241-f48b6168-d071-4223-b737-8f1f9e306d3c.png)
