### ISSUE TITLE
[UI/UX] As a developer, I want to have more focused dashboard, so I can understand faster what is the current status of blocks/peers

### ISSUE THREAD

**Issue by lukasimrich** [openmina/mina-frontend#54]

**Comment by lukasimrich** [comment]
**Week 13**
- [ ]  Current Dashboard updated to show forks, [Figma](https://www.figma.com/file/SEwWpo68UI92SNSookfyTp/UI?node-id=4671-409059&t=vcEVxu22PoBANp6b-4)
![Image](https://user-images.githubusercontent.com/1679939/229515760-c0b303ee-cbcb-413e-b49a-6b52bc8d9a9d.png)

- [ ]  New Page focused on Forks exploration and UI, [Figma](https://www.figma.com/file/SEwWpo68UI92SNSookfyTp/UI?node-id=4586-403408&t=vcEVxu22PoBANp6b-4)
![Image](https://user-images.githubusercontent.com/1679939/229515958-fd4dd4be-dc27-4bdf-aef8-d71d9a900af4.png)

**Comment by lukasimrich** [comment]
Week 15 Overview

**DONE**

- [ ] Simplified Table view of forks
- [ ] Exploring dataviz for node degree, latency, shortest paths, communities
- [ ] Generating mockup data for p2p network, exploring layout engines


**TODO**

- [ ] Narrow and Focus on key features



![Image](https://user-images.githubusercontent.com/1679939/232478271-b5dbcc4e-7829-4f17-beb2-393a08d6cbc4.png)

![Image](https://user-images.githubusercontent.com/1679939/232478330-402d21f3-729f-431d-a5e2-dce2e3bffed2.png)

**Comment by lukasimrich** [comment]
**Week 16**

**DONE**

- [x] Reviewed with FE, adjusted to improve feasibility 



![Image](https://user-images.githubusercontent.com/1679939/233975660-2050b83e-f40d-499c-b3a2-e9101f519470.png)

**Comment by lukasimrich** [comment]
**Week 17**

DONE

- [x] Redesigned to address technical feasibility

![Image](https://user-images.githubusercontent.com/1679939/235431428-45c554e2-29dc-4830-86a0-870006c29686.png)
