### ISSUE TITLE
[UI/UX] As a Mina developer, I want to have an overview of the Snark Worker Coordinator, so I can understand its impact on improving the efficiency of the Snarketplace

### ISSUE THREAD

**Issue by lukasimrich** [openmina/mina-frontend#66]

**Comment by lukasimrich** [comment]
### Week 21

Done 
- [x] Kickoff with Zura
- [x] Initial concept, [Figjam link ](https://www.figma.com/file/yl0z48XRp3PuChPdaGOfgL/Decentralised-Snark-Worker?type=whiteboard&node-id=13%3A2670&t=20rcx9jQpdpZha9z-1)

Todo
- [ ] Iterate the concept, better understand structure of available data, problem we solve

**Comment by lukasimrich** [comment]
### Week 22

Done 
- [x] Initial concept reviewied with Zura
- [x] Concept iterated to include goals, assumptions and UIs
- [x] Initial UIs for Dashboard, Trends, Actions, Scan State
Todo
- [ ]Iterate UIs, get feedback on goals, asssumptions
- [ ]Check feasibility, understand shape of available data
- [ ]Understand  how load/price relates to snark latency


#### Dashboard
![Image](https://github.com/openmina/mina-frontend/assets/1679939/2a1c4804-02d4-4184-b9d9-bb3585253428)

#### Actions Statistics
![Image](https://github.com/openmina/mina-frontend/assets/1679939/15805824-b733-45c1-acce-1e233cb7667c)

#### Trends
![Image](https://github.com/openmina/mina-frontend/assets/1679939/e10dc54e-3209-45fb-acb2-76e57909358e)


#### Scan State
![Image](https://github.com/openmina/mina-frontend/assets/1679939/712d1ec7-1694-4de4-aab8-683aeb21bfed)

**Comment by lukasimrich** [comment]
### Week 23

**Done** 
- [x] Review & Prioritization/Feasibilitty with team **figjam**
- [x] Bootstrap new iteration
- [x] Exploration for Dashboard/Consensus/Scan state

**Todo**
- [ ] Understand  how load/price relates to snark latency


**Boostrap**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/a0630c25-3823-4b09-abdc-65059eb37158)


**Dashboard**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/0a496b67-0bd7-4e85-bbf7-b8b31a466c6b)

*Consensus Exploration*
![Image](https://github.com/openmina/mina-frontend/assets/1679939/a6f67d7d-43f9-45d9-aaf8-04a37be0bbc0)

**Comment by lukasimrich** [comment]
### Week 24

**Done** 
- [x] Live (Dashboard, Frontier) and Historic (Boostrap stats, Actions) views iteration [Figjam](https://www.figma.com/file/yl0z48XRp3PuChPdaGOfgL/Decentralised-Snark-Worker?type=whiteboard&node-id=263-37721&t=ZDDfrF6fMxgZmPih-4)
- [x] Exploration for Scan State to display various layers over a base scan state structure "Layers as in Maps"

**Todo**
- [ ] Get Feedback on Scan State (Goals and UIs) and iterate


**Live and Historic Views**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/a4f667b5-4241-453f-bb32-c5821d264ef1)

**Base scan state layer**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/414adbb1-cf38-45c4-be4d-2942f8b2cb5e)

**TODO and DONE layer**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/640f4072-32fa-431d-9832-28def78827ad)

**Latency layer**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/25d0d37c-c573-46f3-ab20-e8d2460f9906)

**Work Overlap**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/adc8da44-0763-4acc-aaa3-12261e0e5b08)

**Comment by cyrcle0** [comment]
**Week 27**

- [x] WIP: Helping @JanSlobodnik  with producing a diagram illustrating snark worker problem/solution

**Comment by cyrcle0** [comment]
**Week 28**

DONE
- [x] Review logging UI with Alexander
- [x] Update Bootstrap UI based on actual data
- [x] Reviewed illustrations, article, explored animations


TODO
- [ ] Add animations to the article, add missing diagrams
- [ ] Prepare final exports for #71 
 
### Logs with detail sidebar & Frontier visual overview
![Image](https://github.com/openmina/mina-frontend/assets/1679939/076d4945-36db-44fb-9c3c-52986d12b349)

### Bootstrap stats updated
- added totals to table
- sidebar now show distribution and timeserie of the totals value for each category

| Distribution      | Timeserie |
| ----------- | ----------- |
| ![Image](https://github.com/openmina/mina-frontend/assets/1679939/5c7f08c5-99be-4ed9-9ec6-3f6f6638c843)      | ![Image](https://github.com/openmina/mina-frontend/assets/1679939/e402e3e4-1e48-47eb-8172-746b8fe43906)  |

### Article Support #71

**Comment by cyrcle0** [comment]
**Week 29**
DONE
- [x] Node "Live Debug" view to combine live data from transition frontier / traces / logs
- [x] Better diagrams exports for the article

TODO
- [ ] Iterate on the "Live Debug" view
- [ ] Add animations to diagrams with Jan

![Image](https://github.com/openmina/mina-frontend/assets/1679939/672dd218-4beb-4137-852e-8448f34fbdb5)

**Comment by cyrcle0** [comment]
**Week 30**

DONE
- [x] Live Debug Iteration based on feedback [Figma](https://www.figma.com/file/SEwWpo68UI92SNSookfyTp/UI?type=design&node-id=6828-287024&mode=design&t=kWRPBkUIXnUgkaKo-4)

![Image](https://github.com/openmina/mina-frontend/assets/1679939/2cc85ae9-69df-4485-a61d-166629ccbbf9)

**Comment by cyrcle0** [comment]
**Week 31**

DONE
- [x] Workpool Page
- [x] Updated Dashboard Page
- [x] SNARKers Processes Page

---
![Image](https://github.com/openmina/mina-frontend/assets/1679939/0475cfd9-5c8e-426d-9871-26b862605f7e)
---
![Image](https://github.com/openmina/mina-frontend/assets/1679939/4f493e06-778d-449f-8046-85358844bc1b)
---
![Image](https://github.com/openmina/mina-frontend/assets/1679939/38443636-0c19-4b4e-9b10-63690eb4157d)
