### ISSUE TITLE
[UX/UI] As a Developer, I want to have Node diagram and flows, so I can demonstrate how Node works

### ISSUE THREAD

**Issue by cyrcle0** [openmina/mina-frontend#73]

**Comment by cyrcle0** [comment]
**Week 34**

- [x] Initial Research
- [x] Iteration with Zura
- [x] Iteration with Bruno
- [x] Iteration with Sebastien
https://www.figma.com/file/PlFDgJo4wGuRTJlsei5k5k/OpenMina-Work?type=whiteboard&node-id=72-14734&t=wo4rrTItTlzMzwff-4


TODO

- [ ] Review all flows, prepare final version with finalised graphics and layouts

**Comment by cyrcle0** [comment]
**Week 35**

Flows in figma https://www.figma.com/file/PlFDgJo4wGuRTJlsei5k5k/OpenMina-Work?type=whiteboard&node-id=141-28629&t=ex3aH8qgwAlw97SL-4

**DONE**
Reviewed following flows:
 - Bootstrap & Catchup
 - Block received (External Transition)
 - New Transaction added to Transaction Pool
 - New SNARK added to SNARK pool
 - Producing a block (Internal Transition)

**IN PROGRESS**
- Detailed view for Block received (External Transition) - Needs final review
- Overall message flow for Committing and producing a SNARK to showcase parity - Needs several updates
- Detailed P2P Layer Diagrams (Bootstrap, Catchup?)

**TODO**
- Diagram for Detailed Proof system (Currently resolution is prover/verifier, might be useful to showcase traces from https://github.com/orgs/openmina/projects/1/views/15?pane=issue&itemId=32313508)
- Explore MINA codebase, get better idea about naming conventions
- Review the diagrams with Jan

**Comment by cyrcle0** [comment]
**WEEK 37**

https://www.figma.com/file/PlFDgJo4wGuRTJlsei5k5k/OpenMina-Work?type=whiteboard&node-id=141-28629&t=MTXIogGhyLRx83fF-4

**DONE**

- Exploring diagrams to explain Scan State & Witness Folding 
- Explore diagrams for Webnode


**TODO**

- Architecture overview of OCAML node, mapping to Rust

**Comment by cyrcle0** [comment]
**WEEK 38**

**DONE**
- Updated/Added Flows to better distuinguish Web Rust / Server Rust / Server OCaml nodes


https://www.figma.com/file/PlFDgJo4wGuRTJlsei5k5k/OpenMina-Work?type=whiteboard&node-id=141-28629&t=odXlIsntbJ2OcghD-4
![Image](https://github.com/openmina/mina-frontend/assets/1679939/e4d1ed3d-1a41-49f1-aebd-b292ee6195cc)
