### ISSUE TITLE
[UX/UI] As a node developer, I want to view block production status, so I can identify block production failures

### ISSUE THREAD

**Issue by cyrcle0** [openmina/mina-frontend#90]
**DONE**
- [x] Initial Draft
- [x] Revised Version with Design Specs
- [x] FE Support

**TODO**
- [ ] Get Ready for Upcoming Public Testnet Release

[Week 19](https://github.com/openmina/mina-frontend/issues/90#issuecomment-2107501570)
[Week 20](https://github.com/openmina/mina-frontend/issues/90#issuecomment-2120429658)
[Week 21](https://github.com/openmina/mina-frontend/issues/90#issuecomment-2133430204)
[Week 22](https://github.com/openmina/mina-frontend/issues/90#issuecomment-2145143688)

**Comment by cyrcle0** [comment]
**Week 19**

- [x] Research Block Production with Bruno/Vlad/Ado/Zura
- [x] Initial Draft showcasing dashboard key parts
  - VRF Evaluation + Transition Frontier State
  - Block Production
    - Ledger Diff
    - Unproven Block
    - Proof
  - Block Receipt
  - Block Propagation


![Image](https://github.com/openmina/mina-frontend/assets/1679939/11b38d45-e521-4542-9b8c-3526ea84dec3)

**Comment by cyrcle0** [comment]
**Week 20**

- [x] Initial Simplified Design
- [x] Iteration Based on Juraj Feedback

**Design Preview**
![Image](https://github.com/openmina/mina-frontend/assets/1679939/523bd613-6c31-4e57-a143-43defd5b0d48)

**Key States**
-VRF Being calculated after Node started
![Image](https://github.com/openmina/mina-frontend/assets/1679939/026544ba-7ea9-4147-853d-9fa3255fc727)

- Waiting for upcoming Slot
![Image](https://github.com/openmina/mina-frontend/assets/1679939/4e65f701-4bbd-46ed-9673-b31eaf396157)

- Block Production in Progress
![Image](https://github.com/openmina/mina-frontend/assets/1679939/c80c348a-f6a6-4424-bebb-c42f8dc27f2e)

**Comment by cyrcle0** [comment]
**Week 21**
- FE Support
- Making language more accessible, using plain language instead of technical jargon

**Comment by cyrcle0** [comment]
**Week 22**

- [x] FE Support and Iteration
- [x] Testdriving Docker Compose with Local Network

TODOs
- [ ] Prepare updates for upcoming Public Testnet Release
