### ISSUE TITLE
[UX/UI] As a developer I want to see content of Mempool, so I can debug and analyse issues

### ISSUE THREAD

**Issue by cyrcle0** [openmina/mina-frontend#91]
# Mempool UI/UX Feature Summary
Based on https://github.com/openmina/mina-wiki/issues/32#issue-2107954313

### IMPORTANT NOTES
- FE should take care of signing Transactions
- FE should keep track of Time of arrival for Transactions
- Checking invariants violations should be implemented on the BE side
- BE already implemented Search and Sort 

### **MAIN TABLE**
- I tried to adjust the table so it is abstract enough to just fit 3 different kinds of Txs - ZKApp, Delegate, Payment
- I assume that seeing what Txs are **applicable** - ability to be included/applied in a block is crucial
- **Time of Arrival** is another key indicator to spot issues with Txs that got stuck for some reason in mempool
- **Kind** of Transaction, various kinds have various sidebar detail
- Tx **Hash** - useful when we filter and want to see a specific Tx
- **Sender**  + **Nonce** - Again useful as feedback for seeing filtered Tx + We can use it for sorting to see if ordering based on nonce is right
- **Fee** - Enables sorting, this is essential to see what Txs will get applied first
- **Memo** - Besides its generic use, we can mark Generated Transactions here

### **SIDEDETAIL**
- We can use JSON viewer to flexibly display any type of structure
- JSON can display entire data for ZKapp, Delegate and Payment Transactions
- We can even preopen JSONs to see some specific details that matter the most

### **CONTROLLING ELEMENTS**
- Search to find records by Hash/Sender
- Sorting to enable view that are crucial to understand properlyt working mempool - Fee, Same Sender with increasing Nonces
- Filters show at the same time number of resulting elements - this could be useful as a quick table summary
- Actions - Option to generate more transaction, we can have a dedicated place to generate new Txs. It might be useful to start with something that is very easy to modify by expert users - you - eg enter a transaction as a JSON

### **WEEK 23**
- [x] Defining Brief and Scope
- [x] Initial UI/UX Draft
- [x] Adjustments based on Marcin feedback

### **WEEK 24**
- [x] Adding Empty Filter State
- [x] Adjusted New Transaction Form

### **TODO**
- [ ] Feedback from other team members
- [ ] Iteration and FE Support

**Comment by cyrcle0** [comment]
**Week 23**

![Image](https://github.com/openmina/mina-frontend/assets/1679939/35912431-7af2-44a0-b1d4-428a1a072b7e)

**Comment by cyrcle0** [comment]
**Week 24**

![Image](https://github.com/openmina/mina-frontend/assets/1679939/e1920e81-4697-4c36-bbe7-21ee69f1852e)

![Image](https://github.com/openmina/mina-frontend/assets/1679939/be2786e7-c29a-4102-ac56-9a48039e6ae0)
